### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by neico** [Bromvlieg/gm_bromsock#12]
I noticed that the socket is only using AF_NET which effectivly means IPv4 only.
So I'd like to see an option or auto-detection for IPv6 as well (doing a DNS resolve to check for A and AAAA and give AAAA priority, not sure if the native socket has a method for this..., one might want to look at the boost library for advice here as I believe that it has such a detection)

This might impose the need for additional functions to detect if it's IPv4 or IPv6 as protocols differ depending on which is used sometimes (SOCK_RAW being a example, which could by used by passing IPPROTO_ICMP (1) as protocol, tough RAW might not work without special permissions on OS side)

**Comment by Bromvlieg** [comment]
Hey there! It's been almost 9 years since I've made this module, but I got a v2 branch that includes ipv6 support and fixes the issues with references being not propperly cleaned up in the Lua GC.
It's still WIP, but should be up n running in a few weeks. So I'll be closing the issue 😃
