### ISSUE TITLE
[ERROR] addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1: Couldn't load module library!

### ISSUE THREAD

**Issue by SaengerItsWar** [Bromvlieg/gm_bromsock#19]
Hello,
I have this error in the console in Gmod. The bot is Foxedbot and this addon requires the Bromsock Module. The system is Linux Ubuntu

[FoxedBot] Initializing...

[ERROR] addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1: Couldn't load module library!

    require - [C]:-1
    unknown - addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1
    include - [C]:-1
    unknown - addons/foxedbot/lua/autorun/sh_init.lua:15

[ERROR] addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4: attempt to call field 'addCallback' (a nil value)

    unknown - addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4
    include - [C]:-1
    unknown - addons/foxedbot/lua/autorun/sh_init.lua:16

[FoxedBot] Initialized!

**Comment by Bromvlieg** [comment]
Have you tried checking the dependencies with "ldd"? if that doesn't tell you much, you might need to compile it yourself.

**Comment by Saengerkrieg12** [comment]
How you Mean that?

**Comment by Saengerkrieg12** [comment]
can you update the source files pls?

**Comment by Bromvlieg** [comment]
I don't understand what you mean (didn't notice the email, sorry for late reply)

**Comment by Saengerkrieg12** [comment]
i think you must update the binaries for ubuntu
