### ISSUE TITLE
CPU hogging if client fails to connect and you don't manually disconnect it

### ISSUE THREAD

**Issue by Donkie** [Bromvlieg/gm_bromsock#20]
Basically I used this code, and queried 5 different servers every 5 seconds. All of them were not online so the "Failed to connect.." was spamming as planned. However, if I kept this running for more than a minute my computer started lagging to death and soon whole Windows froze because your module is multicore and it was occuping all cores.

When I added the client:Disconnect() it didn't hog up anymore.

I'm not sure if this is intended behavior, but it doesn't seem very intuitive that you have to disconnect from something that failed to connect.

````
function SockSendMessage(ip, port, packet, callback)
	local client = BromSock()

	client:SetCallbackConnect(function(_, ret)
		if not ret then
			if callback then
				callback(false)
			end
			print(string.format("[Sockets] Failed to connect to %s:%s", ip, port))
			client:Disconnect() // <--- this is required!
			return
		end

		client:Send(packet, true)

		if callback then
			client:ReceiveUntil("\r\n")
		else
			client:Disconnect()
		end
	end)

	client:SetCallbackReceive(function(_, pack)
		callback(true, pack)
		client:Disconnect()
	end)

	client:Connect(ip, port)
end

**Comment by Bromvlieg** [comment]
Hey there! This is due how Lua handles the garbage collection, which can take a while. I've improved the way how sockets get cleaned up and threading works, but it'll still cause this issue if the sockets are not reused.

The v2 branch should fix this a bit, but it will still remain. I will be working over the comming weeks to get CI/CD going on and improve this.
