### ISSUE TITLE
Socket Host sending blank/no data to client.

### ISSUE THREAD

**Issue by Deer292** [Bromvlieg/gm_bromsock#25]
I recently tried using Bromsock for a project I am working on, however I have been facing some issues with the Windows build.

I attempted to implement a TCP server, upon testing I discovered that while the message is received by Bromsock OK, when sending a reply, I get a blank response. It's worth noting that I am sending from a non-bromsock client, so I am using the correct methods listed in the ReadMe. 

At first I thought it was an issue with my implementation, however after implementing the HTTP example seen here: https://github.com/Bromvlieg/gm_bromsock/blob/master/Lua_examples/httphost.lua

The same issue occurred, Chrome would report it received an empty response, at this point I was convinced it was a module issue rather than me using the API incorrectly.

I have tried using builds from Github (With and without SSL) and compiling myself, getting the same result every time.

**Comment by Bromvlieg** [comment]
Could you attach a example of your fix so I can look into it? I've been spending time to redo the entire module so would be nice if I can make sure if this is a but that I fix it in the process

**Comment by Deer292** [comment]
@Bromvlieg It was a issue on my end, I was using an application called Packet Sender to test the socket connectivity, and I received a blank response, while with the previous library I was using (GLSock 2) it worked fine, when I turned on TCP Persistent mode, I got the response through.
