### ISSUE TITLE
error in bromsock_C++ allocating buffer to receive 1969627771 bytes

### ISSUE THREAD

**Issue by VaasKahnGrim** [Bromvlieg/gm_bromsock#38]
Basically I have a client setup on garry's mod right now. I can connect and send data out to a listen server just fine. However when attempting to receive data its giving me this error:

```
[ERROR] lua/includes/modules/hook.lua:84: error in bromsock_C++ allocating buffer to receive 1969627771 bytes from IP:PORT
  1. v - [C]:-1
   2. unknown - lua/includes/modules/hook.lua:84
```

The data I'm attempting to recieve is basically a JSON as a string '{"func":"Athenticated"}'

And the code for the bromsock client so far is
```lua
local client = BromSock(BROMSOCK_TCP)

client:SetCallbackConnect(function(sock,ret,ip,port)
	if ret then
		print("Connected to VaasNET")

		local packet_client = BromPacket()
		packet_client:WriteStringRaw('{"username":"'..username..'","password":"'..password..'"}')
		client:Send(packet_client)

		--The moment it has connected the server responds with the JSON string I mentioned.
		client:Receive() --Error only seems to happen when this is here. But otherwise nothing sent to the client is ever read
	else
		print("Failed to connect to: ",ip,port)
	end
end)

client:SetCallbackReceive(function(sock,packet)
	print("Received:	",sock,packet,packet and packet:InSize() or -1)
	print("R_Str:	",packet:ReadString())

	client:Receive()
end)
```

**Comment by Bromvlieg** [comment]
Receive reads 4 bytes if no count is given, so it's trying to read your json as an int. You need to know how big the data is in order to receive it. The `Send` function also inserts 4 bytes as an int.

From the docs:
```
Receive([bytecount])
-- returns packet or false. if no bytecount is given, it will internally call receive(4), read an int from that, and then receive the result of that int.

Send(packet, [dontsendlength])
-- if dontsendlength is true, it WILL NOT add an int in front of the packet to indicate how large the incoming data is. use true if you want to communicate with anything that does not use this way of packeting
```

**Comment by VaasKahnGrim** [comment]
so I just set it to client:Receive(1) and instead of sending JSON as a strong I just sent '1' as a string.
 I also modified the packet:ReadString() in SetCallbackReceive() to use the packet:InSize() and it prints out '1' as it should.

But its only ever receiving that first response, any other it just seems to keep ignoring
```lua
client:SetCallbackReceive(function(sock,packet) --Only ever runs for the first response back from the server, everything else just gets ignored
	print("R_Str:	",packet:ReadString(packet:InSize()))

	client:Receive(packet,packet:InSize())
end)
```

**Comment by VaasKahnGrim** [comment]
managed to resolve the issue after a bit of digging. issue was I wasn't aware bromsock used a think hook so I had to set sv_hibernate_think 1

**Comment by Bromvlieg** [comment]
As a side note, I really should set some time aside to make a V2.0 of this module with all that I learned in C++, the module still being used is amazing :)

**Comment by VaasKahnGrim** [comment]
I set the repo to watch and stared, I'll keep an eye out in the future for a possible V2 😄 I look forward to it

**Comment by VaasKahnGrim** [comment]
A suggestion for when and if you get around to a v2 of bromsock, having a callback for if the socket has timmed out would be great for being able to automatically open back up the connection to a server it was connected to without having to recreate a new socket connection
